language: go

cache:
  directories:
    - "$HOME/google-cloud-sdk/"

services:
- docker

env:
  global:
    - GOOGLE_APPLICATION_CREDENTIALS=~/gcloud-service-key.json
    - PROJECT_NAME_STG=tokencard
    - CLUSTER_NAME_STG=tokencard
    - PROJECT_NAME_PRD=tokencard 
    - CLUSTER_NAME_PRD=tokencard
    - CLOUDSDK_COMPUTE_ZONE=europe-west1-b
    - DOCKER_IMAGE_NAME=eu.gcr.io/true-energy-185810/client
    - KUBE_DEPLOYMENT_NAME=client-deployment
    - KUBE_DEPLOYMENT_CONTAINER_NAME=client
    - NODE_ENV=CI

before_deploy:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update
  - gcloud --quiet components update kubectl

deploy:
  - docker build -f client.dockerfile -t eu.gcr.io/true-energy-185810/client:$TRAVIS_COMMIT .
  - echo $TRAVIS_COMMIT
  - echo $GCLOUD_SERVICE_KEY_STG | base64 --decode -i > ${HOME}/gcloud-service-key.json gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
  - gcloud --quiet config set project tokencard
  - gcloud --quiet config set container/cluster tokencard
  - gcloud --quiet config set compute/zone europe-west1-b
  - gcloud --quiet container clusters get-credentials $CLUSTER_NAME_STG
  - kubectl set image deployment/client-deployment client=eu.gcr.io/true-energy-185810/client:$TRAVIS_COMMIT
